DROP TABLE IF EXISTS Package;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS Customer_Addresses;
DROP TABLE IF EXISTS Contain;
DROP TABLE IF EXISTS Sent_From;
DROP TABLE IF EXISTS Ordered;

CREATE TABLE Package(
PID INTEGER PRIMARY KEY,
Delivery_Address TEXT NOT NULL
);

CREATE TABLE Item(
IID INTEGER PRIMARY KEY, 
Name TEXT NOT NULL, 
Cost REAL CHECK (cost >=0)
);

CREATE TABLE Customer(
CID INTEGER PRIMARY KEY, 
Name TEXT NOT NULL, 
Email TEXT NOT NULL
);

CREATE TABLE Location(
LID INTEGER PRIMARY KEY, 
Name TEXT NOT NULL
);

CREATE TABLE Customer_Addresses(
CID INTEGER,
Address TEXT NOT NULL,
CONSTRAINT fk_CID FOREIGN KEY (CID) REFERENCES Customer(CID)
);

CREATE TABLE Contain(
PID INTEGER,
IID INTEGER,
CONSTRAINT fk_PID FOREIGN KEY (PID) REFERENCES Package(PID),
CONSTRAINT fk_IID FOREIGN KEY (IID) REFERENCES Item(IID)
);

CREATE TABLE Sent_From(
LID INTEGER,
PID INTEGER,
CONSTRAINT fk_LID FOREIGN KEY (LID) REFERENCES Location(LID),
CONSTRAINT fk_PID FOREIGN KEY (PID) REFERENCES Package(PID)
);

CREATE TABLE Ordered(
CID INTEGER,
PID INTEGER,
Day TEXT NOT NULL, 
Month TEXT NOT NULL, 
Year TEXT NOT NULL, 
Time TEXT NOT NULL,
CONSTRAINT fk_CID FOREIGN KEY (CID) REFERENCES Customer(CID),
CONSTRAINT fk_PID FOREIGN KEY (PID) REFERENCES Package(PID)
);